### ISSUE TITLE
Add correct copyright

### ISSUE THREAD

**Issue by Mukarillo** [Berklee-Game-Audio/Unity-Wwise-Tetris#1]
Hello,

I was going through my repositories and I found this repository that shares the exact same code as mine, with only a few alterations and additions.
Although I find very good and flattered that you are using what I did, you are breaching licence conditions by not including the correct copyright to my username.
Please, fix your LICENSE.md file to include the original license.

When you cloned my project the following phrase was in the [Licensing](https://github.com/Mukarillo/UnityTetris/blob/master/LICENSE):
`The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.`

Also, if you want to give credit to the original repository, I would be very glad 👍

Thanks!

**Comment by msweet37** [comment]
Hi - I'm very sorry, a student pulled this, and I didn't check it.  Berklee has been using it as a student template.  I will update the license file, and credit you at the very least.  I can make those updates tomorrow (Thursday).  If you'd like me to delete it, I can also do that.  Again, my apologies. 
Best -M

**Comment by Mukarillo** [comment]
No problem at all, the project was made to be shared and to people use however they want.
Just adding the correct License is enough. Adding the credit is very welcomed :) 

Thanks again!

**Comment by msweet37** [comment]
Thank you.  I updated the Github license, and credit you in the ReadMe, as well as in the license directly.  If you want any additional modifications please let me know.  And thanks for allowing us to use it.
